# Generated by Django 4.1.1 on 2023-07-16 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_invoice_is_stock_updated_after_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_products',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 16, 7, 0, 23, 82295, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
